# Laboratorio 5: Clasificación 🤗

<center><strong>MDS7202: Laboratorio de Programación Científica para Ciencia de Datos - Primavera 2025</strong></center>


### Cuerpo Docente:

- Profesores: Diego Cortez, Gabriel Iturra
- Auxiliares: Melanie Peña, Valentina Rojas
- Ayudantes: Nicolás Cabello, Cristopher Urbina

### Equipo: SUPER IMPORTANTE - notebooks sin nombre no serán revisados

- Nombre de alumno 1: Santiago Haberle
- Nombre de alumno 2: Francisco Márquez

### **Link de repositorio de GitHub:** [Insertar Repositorio](https://github.com/fco-marquez/MDS7202_Free_Riders)

### Temas a tratar
- Clasificación en problemas desbalanceados
- Lightgbm y xgboost
- Pipelines

## Reglas:

- **Grupos de 2 personas**
- Fecha de entrega: Entregas Martes a las 23:59.
- Instrucciones del lab el viernes a las 16:15 en formato online. Asistencia no es obligatoria, pero se recomienda **fuertemente** asistir.
- <u>Prohibidas las copias</u>. Cualquier intento de copia será debidamente penalizado con el reglamento de la escuela.
- Tienen que subir el laboratorio a u-cursos y a su repositorio de github. Labs que no estén en u-cursos no serán revisados. Recuerden que el repositorio también tiene nota.
- Cualquier duda fuera del horario de clases al foro. Mensajes al equipo docente serán respondidos por este medio.
- Pueden usar cualquier material del curso que estimen conveniente.





### Objetivos principales del laboratorio
- Comprender cómo trabajar con problemas de clasificación con clases desbalanceadas.
- Aplicar los modelos lightgbm y xgboost.
- Practicar Pipelines

# Parte Teórica [12 puntos]




1. Explique cuál es la diferencia entre los datos de entrenamiento y validación. [1 punto]

2. Explique cuál es el principal desafío al trabajar problemas de clasificación con data no supervisada. [1 punto]

3. Explique en **sus palabras** qué es la matriz de confusión y para qué se utiliza. [1 puntos]

4. Escriba la fórmula de las siguientes métricas y explique con **sus palabras** cómo se interpretan. [1 punto cada uno]

  * Accuracy
  * Precision
  * Recall
  * F1 score

5. Explique qué métrica recomendaría para los siguientes contextos de clasificación. [1 punto cada uno]

  * Mantenimiento predictivo de fallas de maquinaria pesada en la industria minera.  
  * Detección de enfermedades altamente contagiosas.
  * Aprobación de créditos de alto riesgo.
  * Detección de crímenes.

6. Explique qué es la calibración de modelos y para qué se usa. [1 punto]


**Respuesta:**

1. La diferencia entre los datos de entrenamiento y validación es que los primeros se utilizan para entrenar los modelos, es decir, a partir de estos se aprenden. Por otro lado, los de validación son aquellos que se utilizan para seleccionar el mejor modelo al ir variando sus hiperparámetros.
2. El principal desafío en la clasificación no supervisada es la ausencia de una clase objetivo, lo que complica tanto la evaluación del modelo como la interpretación de los resultados. Sin etiquetas reales no pueden aplicarse métricas tradicionales, debiendo recurrir a indicadores alternativos que suelen ser subjetivos y no siempre fiables. Además, los grupos generados por el algoritmo no necesariamente corresponden a categorías útiles o representativas de la realidad, lo que dificulta validar su relevancia.
3. La matriz de confusión es una tabla que permite evaluar el desempeño de un modelo de clasificación comparando las etiquetas reales con las predicciones del modelo. En ella, las filas representan las clases reales y las columnas las clases predichas (o viceversa), mostrando cuántas observaciones fueron correctamente clasificadas y cuántas se confundieron entre categorías.
A partir de esta matriz se pueden calcular métricas clave como precisión (precision), recall o sensibilidad, especificidad, exactitud (accuracy), entre otras.
4. * Accuracy se calcula como (TP + TN) / (TP + TN + FP + FN) y mide la proporción de aciertos totales del modelo, siendo útil cuando las clases están balanceadas, pero puede ser engañosa si una clase es mucho más frecuente que la otra.
    * Precision se calcula como TP / (TP + FP) y representa qué tan confiables son las predicciones positivas, es decir, de todos los casos que el modelo clasificó como positivos, cuántos realmente lo eran.

    * Recall se calcula como TP / (TP + FN) y mide la capacidad del modelo para encontrar todos los casos positivos reales, siendo clave cuando es más importante no dejar pasar positivos sin detectar (Por ejemplo el ejemplo clásico de detección de enfermedades).

    * F1 score se calcula como 2 * (Precision * Recall) / (Precision + Recall). Así, vemos que es una ponderación entre precisión y recall, siendo especialmente útil cuando se busca un balance entre evitar falsos positivos y no perder falsos negativos.
5. Métricas recomendadas:
    1. Métrica recomendada: Recall. En este escenario es crítico no dejar pasar fallas reales (falsos negativos), ya que una falla no detectada puede generar altos costos y riesgos de seguridad.
    2. Métrica recomendada: Recall. Aquí lo más importante es identificar a todos los enfermos, incluso si eso implica tener algunos falsos positivos. No detectar a una persona contagiada puede propagar la enfermedad.
    3. Métrica recomendada: Precision. En este caso, aprobar erróneamente un crédito a alguien que no lo pagará (falso positivo) tiene un alto costo económico.
    4. Métrica recomendada: F1 score. La detección de crímenes requiere un equilibrio: no dejar pasar delitos (recall) pero también evitar falsas acusaciones (precision).
6. La calibración consiste en ajustar las probabilidades que entrega un modelo sobre la clasificación de una cierta etiqueta con respecto a la probabilidad real de que esa etiqueta realmente ocurra. Tienen principal importancia en contextos donde los eventos o categorías predichas son poco frecuentes o son muy importantes de ser acertados, y se usa pues si bien un modelo puede predecir bien, no siempre se condice con la realidad.

# Parte práctica [48 puntos]

<p align="center">
  <img src="https://drive.google.com/uc?export=view&id=1BnO4tyh3vM2P199Ec9s3JjngQ4qQ9seP"
" width="300">
</p>


Tras el trágico despido de la mítica mascota de Maipú, Renacín decide adentrarse como consultor en el mercado futbolero, el cuál (para variar...) está cargado en especulaciones.

Como su principal tarea será asesorar a los directivos de los clubes sobre cuál jugador comprar y cuál no, Renacín desea generar modelos predictivos que evaluén distintas características de los jugadores; todo con el fin de tomar decisiones concretas basadas en los datos.

Sin embargo, su condición de corporeo le impidió tomar la versión anterior de MDS7202, por lo que este motivo Renacín contrata a su equipo para lograr su objetivo final. Dado que aún tiene fuertes vínculos con la dirección de deportes de la municipalidad, el corporeo le entrega base de datos con las estadísticas de cada jugador para que su equipo empieze a trabajar ya con un dataset listo para ser usado.


**Los Datos**

Para este laboratorio deberán trabajar con el csv `statsplayers.csv`, donde deberán aplicar algoritmos de aprendizaje supervisado de clasificación en base a características que describen de jugadores de fútbol.

Para comenzar cargue el dataset señalado y a continuación vea el reporte **`Player_Stats_Report.html`** (adjunto en la carpeta del enunciado) que describe las características principales del `DataFrame`.

In [36]:
try:
    import pycaret
    print("PyCaret already installed ✅")
except ImportError:
    !pip install --pre pycaret[full]


PyCaret already installed ✅


In [37]:
# Si usted está utilizando Colabolatory le puede ser útil este código para cargar los archivos.
try:
    from google.colab import drive
    drive.mount("/content/drive")
    path = '/content/drive/MyDrive/lab_mds'
except:
    print('Ignorando conexión drive-colab')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


## 1. Predicción de Seleccionados Nacionales [14 puntos]

<p align="center">
  <img src="https://www.futuro.cl/wp-content/uploads/2016/06/chile-argentina-meme-12.jpg" width="300">
</p>



### 1.1 Preprocesamiento [5 puntos]

Tareas:

1. Genere los labels para la clasificación binaria en una variable llamada `label`. Para esto, trabaje sobre el atributo `National_Position` suponiendo que los valores nulos son jugadores no seleccionados para representar a su país. [Sin puntaje]

2. Hecho esto, ¿cuántos se tienen ejemplos por cada clase? Comente lo que observa. [1 punto]

3. Genere un `ColumnTransformer` en donde especifique las transformaciones que hay que realizar para cada columna (por ejemplo StandarScaler, MinMaxScaler, OneHotEncoder, etc...) para que puedan ser utilizadas correctamente por el modelo predictivo y guárdelo una variable llamada `col_transformer`. [2 puntos]

4. Comente y justifique las transformaciones elegidas sobre cada una de las variables (para esto utilice el material `Player_Stats_Report.html` que viene en el zip del lab), al igual que las transformaciones aplicadas. [2 puntos]

**Respuesta:**

### 1

In [38]:
import pandas as pd
df = pd.read_csv(path+"/stats_players.csv")
df_label = df.copy()
df_label["label"] = df["National_Position"].apply(lambda x: 0 if  pd.isna(x) else 1)
df_label.head()

Name Nationality National_Position Club_Position  Height  \
0  Cristiano Ronaldo    Portugal                LS            LW     185   
1       Lionel Messi   Argentina                RW            RW     170   
2             Neymar      Brazil                LW            LW     174   
3        Luis Suárez     Uruguay                LS            ST     182   
4       Manuel Neuer     Germany                GK            GK     193   

   Weight Preffered_Foot  Age        Work_Rate  Weak_foot  ...  Jumping  \
0      80          Right   32       High / Low          4  ...       95   
1      72           Left   29  Medium / Medium          4  ...       68   
2      68          Right   25    High / Medium          5  ...       61   
3      85          Right   30    High / Medium          4  ...       69   
4      92          Right   31  Medium / Medium          4  ...       78   

   Heading  Shot_Power  Finishing  Long_Shots  Curve  Freekick_Accuracy  \
0       85          92         93          90     81                 76   
1       71          85         95          88     89                 90   
2       62          78         89          77     79                 84   
3       77          87         94          86     86                 84   
4       25          25         13          16     14                 11   

   Penalties  Volleys  label  
0         85       88      1  
1         74       85      1  
2         81       83      1  
3         85       88      1  
4         47       11      1  

[5 rows x 40 columns]

### 2

In [39]:
df_label["label"].value_counts()

label
0    16513
1     1075
Name: count, dtype: int64

Vemos que hay 16513 valores nulos, representando así la clase 0, de jugaodres no seleccionados para jugar. Por su parte, los jugadores seleccionados tienen 1075 ejemplos con label = 1, siendo lógico, ya que son pocos los jugadores que representan a su país vs el total de jugadores.

### 3

In [40]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder, MinMaxScaler

df_transform = df_label.copy().drop(columns=["National_Position", "Name"])
ordinal = ["Weak_foot","Skill_Moves"]
numeric_features = df_transform.select_dtypes(include="number").drop(columns=ordinal).drop(columns=["label"]).columns.tolist()
categorical = df_transform.select_dtypes("object").columns.tolist()

col_transformer = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), numeric_features),
        ("categorical", OneHotEncoder(handle_unknown="ignore"), categorical),
        ("ordinal", MinMaxScaler(), ordinal)
    ]
)


### 4

De partida, eliminamos nation_position y name, ya que la primera implicaría un data_leakage sobre la variable objetivo label, y name no aporta nada al modelo aparte de tenre una cardinalidad enorme.

Viendo el html provisto, la gran mayoría de los atributos son valores numéricos entre 0 y 100 aproximadamente (Peso y altura difieren pero están en la misma escala aprox), además de distribuir casi como una normal. De esta forma, simplemente aplicamos un estandar scaler sobre estos. Sin embargo, hay un par de valores numéricos que son ordinales, siendo estos Weak_foot y Skill_moves, representando la habilidad de cada jugador sobre cada una, con un orden definido (0 muy malo, 5 muy bueno). Para esto, apicamos MinMaxScaler. Por último, a los categoricals, aplicamos un one hot encoder para cada una, teniendo así columnas binarias para cada valor.

### 1.2 Entrenamiento [3 puntos]

Ahora, vamos a entrenar los pipelines generados en los pasos anteriores. Para esto, debe realizar las siguientes tareas:

1. Separe los datos de entrenamiento en un conjunto de entrenamiento y de prueba  (la proporción queda a su juicio). En este paso, seleccione los ejemplos de forma aleatoria e intente mantener la distribución original de labels de cada clase en los conjuntos de prueba/entrenamiento. (vea la documentación de `train_test_split`). [1 puntos]


2. Defina un pipeline llamado `pipeline_xgboost` y otro llamado `pipeline_lightgbm`. Estos pipelines deben tener el mismo ColumnTransformer definido en la sección de preprocesamiento, pero deben variar los clasificadores de acuerdo al nombre de cada pipeline. [1 puntos]

3. Entrene los pipelines. [1 punto]



**Respuesta:**

In [41]:
from sklearn.model_selection import train_test_split

X = df_transform.drop(columns=["label"])
y = df_transform["label"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=1892, stratify=y
)

Analizando la distribución de la variable objetivo en el punto anterior, tenemos aproximadamente 3500 datos aprox para validar nuestros resultados y 14 mil datos de entrenamiento. Viendo que hay casi mil ejemplos de la variable objetivo, con casi el triple de datos de validacion con respecto a ese numero, debiesemos estar bien en especial al mantener las proporciones con stratify.

In [42]:
from sklearn.pipeline import Pipeline
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

pipeline_xgboost = Pipeline(steps=[
    ("preprocess", col_transformer),
    ("clf", XGBClassifier(
        random_state=1892,
    ))
])

pipeline_lightgbm = Pipeline(steps=[
    ("preprocess", col_transformer),
    ("clf", LGBMClassifier(
        random_state=1892
    ))
])


In [43]:
# Entrenar XGBoost
pipeline_xgboost.fit(X_train, y_train)

Pipeline(memory=None,
         steps=[('preprocess',
                 ColumnTransformer(n_jobs=None, remainder='drop',
                                   sparse_threshold=0.3,
                                   transformer_weights=None,
                                   transformers=[('num',
                                                  StandardScaler(copy=True,
                                                                 with_mean=True,
                                                                 with_std=True),
                                                  ['Height', 'Weight', 'Age',
                                                   'Ball_Control', 'Dribbling',
                                                   'Marking', 'Sliding_Tackle',
                                                   'Standing_Tackle',
                                                   'Aggression', 'Reactions',
                                                   'Interceptions', '...
                               importance_type=None,
                               interaction_constraints=None, learning_rate=None,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=None, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=None, n_jobs=None,
                               num_parallel_tree=None,
                               objective='binary:logistic', ...))],
         verbose=False)

In [44]:
# Entrenar LightGBM
pipeline_lightgbm.fit(X_train, y_train)


[LightGBM] [Info] Number of positive: 860, number of negative: 13210
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001905 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2683
[LightGBM] [Info] Number of data points in the train set: 14070, number of used features: 143
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.061123 -> initscore=-2.731797
[LightGBM] [Info] Start training from score -2.731797


Pipeline(memory=None,
         steps=[('preprocess',
                 ColumnTransformer(n_jobs=None, remainder='drop',
                                   sparse_threshold=0.3,
                                   transformer_weights=None,
                                   transformers=[('num',
                                                  StandardScaler(copy=True,
                                                                 with_mean=True,
                                                                 with_std=True),
                                                  ['Height', 'Weight', 'Age',
                                                   'Ball_Control', 'Dribbling',
                                                   'Marking', 'Sliding_Tackle',
                                                   'Standing_Tackle',
                                                   'Aggression', 'Reactions',
                                                   'Interceptions', '...
                 LGBMClassifier(boosting_type='gbdt', class_weight=None,
                                colsample_bytree=1.0, importance_type='split',
                                learning_rate=0.1, max_depth=-1,
                                min_child_samples=20, min_child_weight=0.001,
                                min_split_gain=0.0, n_estimators=100,
                                n_jobs=None, num_leaves=31, objective=None,
                                random_state=1892, reg_alpha=0.0,
                                reg_lambda=0.0, subsample=1.0,
                                subsample_for_bin=200000, subsample_freq=0))],
         verbose=False)

### 1.3 Resultados [6 puntos]

1. Calcule las métricas accuracy, precisión y recall de la clase positiva (la que indica que un jugador es seleccionado nacional) para evaluar el rendimiento de los distintos modelos. Verifique sus resultados usando `classification_report`. [2 puntos]

2. Explique qué implican los valores de accuracy, precisión y recall de la clase positiva (la que indica que un jugador es seleccionado nacional) y cómo influye la cantidad de ejemplos por clase en los resultados obtenidos. [2 puntos]

3. Explique qué métrica le parece más adecuada y concluya qué modelo tiene un mejor desempeño. [2 puntos]

**Respuesta:**

### 1.

In [45]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, classification_report, f1_score

# Predicciones
y_pred_xgb = pipeline_xgboost.predict(X_test)
y_pred_lgb = pipeline_lightgbm.predict(X_test)

# XGBoost
acc_xgb = accuracy_score(y_test, y_pred_xgb)
prec_xgb = precision_score(y_test, y_pred_xgb)
rec_xgb = recall_score(y_test, y_pred_xgb)

print("XGBoost")
print("Accuracy:", acc_xgb)
print("Precision:", prec_xgb)
print("Recall:", rec_xgb)
print(classification_report(y_test, y_pred_xgb))

# LightGBM
acc_lgb = accuracy_score(y_test, y_pred_lgb)
prec_lgb = precision_score(y_test, y_pred_lgb)
rec_lgb = recall_score(y_test, y_pred_lgb)

print("\nLightGBM")
print("Accuracy:", acc_lgb)
print("Precision:", prec_lgb)
print("Recall:", rec_lgb)
print(classification_report(y_test, y_pred_lgb))


XGBoost
Accuracy: 0.9499715747583855
Precision: 0.6666666666666666
Recall: 0.3627906976744186
              precision    recall  f1-score   support

           0       0.96      0.99      0.97      3303
           1       0.67      0.36      0.47       215

    accuracy                           0.95      3518
   macro avg       0.81      0.68      0.72      3518
weighted avg       0.94      0.95      0.94      3518


LightGBM
Accuracy: 0.9516770892552586
Precision: 0.6859504132231405
Recall: 0.386046511627907
              precision    recall  f1-score   support

           0       0.96      0.99      0.97      3303
           1       0.69      0.39      0.49       215

    accuracy                           0.95      3518
   macro avg       0.82      0.69      0.73      3518
weighted avg       0.94      0.95      0.95      3518



### 2.

Accuracy (~0.95 en ambos modelos): indica que alrededor del 95 % de las predicciones totales fueron correctas. Sin embargo, este valor es engañoso porque la clase negativa (jugadores no seleccionados) es muy mayoritaria (3303 vs. 215). El modelo puede obtener una alta exactitud simplemente acertando a la mayoría de los “no seleccionados”.

Precisión (≈0.67–0.69 para la clase positiva): de todos los jugadores que el modelo predijo como seleccionados, solo alrededor del 67–69 % realmente lo son. Es decir, hay una proporción relevante de falsos positivos, aunque no es excesiva.

Recall (≈0.36–0.39 para la clase positiva): de todos los jugadores que realmente son seleccionados, el modelo solo logra detectar entre 36 % y 39 %. Esto significa que pierde a más de la mitad de los seleccionados reales (alto número de falsos negativos).

Influencia del desbalance: la gran diferencia en la cantidad de ejemplos (clase 0 ≫ clase 1) hace que el modelo aprenda a priorizar la clase mayoritaria para maximizar accuracy, sacrificando la detección de los pocos casos positivos, lo que explica el recall tan bajo.

### 3.

Dado que el objetivo es identificar correctamente a los jugadores seleccionados nacionales (clase positiva), es más crítico no perder casos verdaderos, por lo que el recall es la métrica más importante. LightGBM tiene un recall ligeramente mayor (0.39 vs 0.36) y también una precisión algo superior (0.69 vs 0.67), manteniendo prácticamente el mismo accuracy. Por lo tanto, LightGBM presenta un mejor equilibrio entre detectar seleccionados y evitar falsos positivos, siendo el modelo con mejor desempeño para este problema.

## 2. Predicción de posiciones de jugadores [4 puntos]

<p align="center">
  <img src="https://pbs.twimg.com/media/E1rfA1aWEAYU6Ny.jpg" width="300">
</p>

En una nueva jornada de desmesuradas transacciones deportivas, Renacín escuchó a sus colegas discutir acerca de que el precio de cada jugador depende en gran medida de la posición en la cancha en la que juega. Y además, que hay bastantes jugadores nuevos que no tienen muy claro en que posición verdaderamente brillarían, por lo que actualmente puede que actualmente estén jugando en posiciones sub-optimas.

Viendo que los resultados del primer análisis no son tan esperanzadores, el corporeo los comanda a cambiar su tarea: ahora, les solicita que construyan un clasificador enfocado en predecir la mejor posición de los jugadores en la cancha según sus características.

Para lograr esto, primero, les pide que etiqueten de la siguiente manera los valores que aparecen en el atributo `Club_Position`, pidiendo que agrupen los valores en los siguientes grupos:

**Nota**:  Renacín les recalca que **no deben utilizar los valores ```Sub``` y ```Res``` de esta columna**.

```python
ataque = ['ST', 'CF']
central_ataque = ['RW', 'CAM', 'LW']
central = ['RM', 'CM', 'LM']
central_defensa = ['RWB', 'CDM', 'LWB']
defensa = ['RB', 'CB', 'LB']
arquero = ['GK']
```

La elección del clasificador se justificar en base a la siguiente [guía](https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html) y se deben comentar los resultados obtenidos en la clasificación.

**Tareas:** [1 punto por tarea]

1. En un nuevo dataframe, aplique las etiquetas descritas anteriormente en cada uno de los valores señalados en esta sección y guárdelos en la variable `label`.
2. Cuente cuántos por clase quedan.
3. Entrene el nuevo pipeline y ejecute una evaluación de este.  
4. Comente los resultados obtenidos.



**Respuesta:**

### 1.

In [46]:
# Agregamos algunas posiciones faltantes según nuestra lógica y lo de la guía

ataque = ['ST', 'CF', 'LF', 'RF', 'LS', 'RS']
central_ataque = ['RW', 'CAM', 'LW', 'RAM', 'LAM']
central = ['RM', 'CM', 'LM', 'RCM', 'LCM']
central_defensa = ['RWB', 'CDM', 'LWB', 'LDM', 'RDM']
defensa = ['RB', 'CB', 'LB', 'LCB', 'RCB']
arquero = ['GK']

In [47]:
def assign_group(pos):
  if pos in ataque:
    return "ataque"
  elif pos in central_ataque:
    return "central_ataque"
  elif pos in central:
    return "central"
  elif pos in central_defensa:
    return "central_defensa"
  elif pos in defensa:
    return "defensa"
  elif pos in arquero:
    return "arquero"

df_pos = df_label.copy().dropna(subset=["Club_Position"])
df_pos = df_pos[df_pos["Club_Position"] != "Sub"]
df_pos = df_pos[df_pos["Club_Position"] != "Res"]
df_pos["label"] = df_pos["Club_Position"].apply(assign_group)
df_pos.head()

Name Nationality National_Position Club_Position  Height  \
0  Cristiano Ronaldo    Portugal                LS            LW     185   
1       Lionel Messi   Argentina                RW            RW     170   
2             Neymar      Brazil                LW            LW     174   
3        Luis Suárez     Uruguay                LS            ST     182   
4       Manuel Neuer     Germany                GK            GK     193   

   Weight Preffered_Foot  Age        Work_Rate  Weak_foot  ...  Jumping  \
0      80          Right   32       High / Low          4  ...       95   
1      72           Left   29  Medium / Medium          4  ...       68   
2      68          Right   25    High / Medium          5  ...       61   
3      85          Right   30    High / Medium          4  ...       69   
4      92          Right   31  Medium / Medium          4  ...       78   

   Heading  Shot_Power  Finishing  Long_Shots  Curve  Freekick_Accuracy  \
0       85          92         93          90     81                 76   
1       71          85         95          88     89                 90   
2       62          78         89          77     79                 84   
3       77          87         94          86     86                 84   
4       25          25         13          16     14                 11   

   Penalties  Volleys           label  
0         85       88  central_ataque  
1         74       85  central_ataque  
2         81       83  central_ataque  
3         85       88          ataque  
4         47       11         arquero  

[5 rows x 40 columns]

In [48]:
df_pos["Club_Position"].unique()

array(['LW', 'RW', 'ST', 'GK', 'RCM', 'CAM', 'LCB', 'LCM', 'RS', 'RB',
       'RCB', 'LM', 'LDM', 'RM', 'LB', 'CDM', 'RDM', 'LF', 'CB', 'LAM',
       'CM', 'LS', 'RF', 'RWB', 'RAM', 'LWB', 'CF'], dtype=object)

### 2.

In [49]:
df_pos["label"].value_counts()

label
defensa            2444
central            1614
ataque              865
central_defensa     741
central_ataque      653
arquero             632
Name: count, dtype: int64

### 3.

In [50]:
df_pos_transform = df_pos.copy().drop(columns=["National_Position", "Name", "Club_Position"])
ordinal = ["Weak_foot","Skill_Moves"]
numeric_features = df_pos_transform.select_dtypes(include="number").drop(columns=ordinal).columns.tolist()
categorical = df_pos_transform.select_dtypes("object").drop(columns=["label"]).columns.tolist()

pos_col_transformer = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), numeric_features),
        ("categorical", OneHotEncoder(handle_unknown="ignore"), categorical),
        ("ordinal", MinMaxScaler(), ordinal)
    ]
)

In [51]:
X = df_pos_transform.drop(columns=["label"])
y = df_pos_transform["label"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=1892, stratify=y
)

In [52]:
from sklearn.svm import LinearSVC

pipeline_linear_svc = Pipeline(steps=[
    ("preprocess", pos_col_transformer),
    ("svc", LinearSVC())
])


In [53]:
pipeline_linear_svc.fit(X_train, y_train)

Pipeline(memory=None,
         steps=[('preprocess',
                 ColumnTransformer(n_jobs=None, remainder='drop',
                                   sparse_threshold=0.3,
                                   transformer_weights=None,
                                   transformers=[('num',
                                                  StandardScaler(copy=True,
                                                                 with_mean=True,
                                                                 with_std=True),
                                                  ['Height', 'Weight', 'Age',
                                                   'Ball_Control', 'Dribbling',
                                                   'Marking', 'Sliding_Tackle',
                                                   'Standing_Tackle',
                                                   'Aggression', 'Reactions',
                                                   'Interceptions', '...
                                                 ('ordinal',
                                                  MinMaxScaler(clip=False,
                                                               copy=True,
                                                               feature_range=(0,
                                                                              1)),
                                                  ['Weak_foot',
                                                   'Skill_Moves'])],
                                   verbose=False,
                                   verbose_feature_names_out=True)),
                ('svc',
                 LinearSVC(C=1.0, class_weight=None, dual='warn',
                           fit_intercept=True, intercept_scaling=1,
                           loss='squared_hinge', max_iter=1000,
                           multi_class='ovr', penalty='l2', random_state=None,
                           tol=0.0001, verbose=0))],
         verbose=False)

### 4.

In [54]:
# Predicciones
y_pred_svc = pipeline_linear_svc.predict(X_test)

# XGBoost
prec_svc = precision_score(y_test, y_pred_svc, average="weighted")
rec_svc = recall_score(y_test, y_pred_svc, average="weighted")
f1_svc = f1_score(y_test, y_pred_svc, average="weighted")

print("Linear_SVC")
#print("Accuracy:", acc_svc)
print("Precision:", prec_svc)
print("Recall:", rec_svc)
print("F1 Score:", f1_svc)
print(classification_report(y_test, y_pred_svc))


Linear_SVC
Precision: 0.7151260893333791
Recall: 0.7323741007194244
F1 Score: 0.7114676875505814
                 precision    recall  f1-score   support

        arquero       1.00      1.00      1.00       126
         ataque       0.77      0.87      0.82       173
        central       0.55      0.65      0.59       323
 central_ataque       0.52      0.22      0.31       131
central_defensa       0.56      0.30      0.39       148
        defensa       0.83      0.94      0.88       489

       accuracy                           0.73      1390
      macro avg       0.70      0.66      0.67      1390
   weighted avg       0.72      0.73      0.71      1390



En primera instancia, elegimos un modelo LinearSVC según el recurso de elección de modelos provisto por el enunciado y las características del dataset. Con esto, vemos que los resultados demuestran un mucho mejor desempeño con respecto al modelo anterior. Vemos que clasifica muy bien los arqueros, siendo algo lógico pues si bien son muy pocos tienen una distribución de atributos completamente distinta a los otros jugadores. También se desempeña bien en defensa y ataque, que son clases con muchos ejemplos y relativamente homogéneas, por lo que el modelo tiene suficiente información para aprenderlas correctamente.

En cambio, las posiciones centrales y las combinadas como central_defensa y central_ataque son más difíciles. Esto refleja dos factores: primero, hay menos ejemplos de estas clases en el dataset, lo que dificulta que el modelo aprenda patrones claros; segundo, futbolísticamente son roles híbridos que combinan características de defensa y ataque, por lo que sus estadísticas se parecen entre sí y generan confusión para el modelo.

En resumen, el desempeño del modelo está muy ligado al desbalance de clases: las posiciones con más datos y más definidas se predicen bien, mientras que las clases con menos ejemplos o con roles intermedios tienen baja precisión y recall, lo que limita la capacidad de diferenciar correctamente a todos los jugadores.

## 3. Predicciones de Seleccionados Nacionales para el Jere Klein [30 puntos]

<center>
<img src='https://www.radioactiva.cl/wp-content/uploads/2024/04/Jere-Klein-1-768x432.webp' width=500 />

Después de alcanzar la fama como cantante urbano, Jere Klein decide explorar una nueva faceta. Con su amor por el fútbol y convencido de que los artistas urbanos poseen un talento y versatilidad excepcionales, Jere se embarca en un proyecto innovador: desarrollar un sistema de inteligencia artificial capaz de identificar a jugadores que tienen potencial para convertirse en futbolistas profesionales. Su teoría es que muchos artistas del género urbano chileno, con sus habilidades únicas y su disciplina, podrían destacarse también en el deporte. Con este sistema, Jere espera no solo abrir nuevas oportunidades para sus colegas artistas, sino también demostrar la amplia gama de talentos que pueden ofrecer.

### 2.1 ¿Qué modelo de árbol es más de "pana"? [10 puntos]

<center>
<img src='https://64.media.tumblr.com/39189215a7d3d96823cb359f35b44e05/tumblr_psmrhrR3Xw1qf5hjqo4_540.gif' width=300 />


**Tareas**


1. Considerando el la variable llamada `label` creada en la sección 1.1. Para determinar cuál modelo de árbol sería más adecuado para la tarea en cuestión, utilice PyCaret. Este deberá centrarse exclusivamente en modelos de tipo árbol. Jere ha especificado que busca un modelo que tome decisiones rápidamente y que tenga una baja tasa de falsos positivos, ya que planea invertir en estos jugadores. [3 puntos]

Para la comparación, utilice los siguientes modelos:

```python
['et', 'rf', 'dt', 'xgboost', 'lightgbm', 'catboost']
```

2. Explique en brevemente que son los modelos de la siguiente lista `['et', 'rf', 'dt']` y como funcionan. [3 punto]

3. Tras realizar la comparación de modelos, seleccione aquel que muestre el mejor rendimiento en términos de velocidad y precisión, especialmente en la reducción de falsos positivos. Utilice la función `evaluate_model` de PyCaret para revisar y analizar los resultados obtenidos en los siguientes aspectos:

  - **Confusión Matrix**: ¿Cómo se encuentran la tasa de verdaderos positivos y verdaderos negativos?
  - **Threshold**: ¿Es acaso el umbral por defecto del modelo el mejor para las predicciones?
  - **Feature Importance**: ¿Cuáles son las variables con mejor desempeño? ¿A qué podría deberse esto?
  - **Learning Curve**: ¿El modelo presenta algún problema?

  [4 puntos]

**Respuesta**

### 1.

In [55]:
from pycaret.datasets import get_data
from pycaret.classification import *
import os

os.environ["PYCARET_CUSTOM_LOGGING_LEVEL"] = "CRITICAL"

#Continuar código aquí

clf = setup(data=df_transform, target='label', session_id = 8647)

# Modelos de árboles a comparar
models_to_compare = ['et', 'rf', 'dt', 'xgboost', 'lightgbm', 'catboost']

best_model = compare_models(include=models_to_compare, sort = "Precision")


Processing:   0%|          | 0/29 [00:00<?, ?it/s]

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [66]:
lightgbm = create_model('lightgbm')

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

In [67]:
# Seleccionamos como mejor modelo el XGBoost
best_model = lightgbm

In [68]:
evaluate_model(best_model)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

### 2.
* dt (Decision Tree – Árbol de Decisión)
Es un modelo que divide los datos en ramas jerárquicas de decisiones basadas en las características (features). En cada nodo se elige la variable y el umbral que mejor separa las clases (por ejemplo, usando Gini o entropy). El resultado es un árbol en el que cada hoja representa una predicción.

* rf (Random Forest – Bosque Aleatorio)
Es un ensamble de muchos árboles de decisión independientes. Cada árbol se entrena con una muestra aleatoria de los datos y un subconjunto de características, y la predicción final se obtiene por votación mayoritaria (clasificación) o promedio (regresión). Esto reduce el sobreajuste típico de un solo árbol y mejora la precisión.

* et (Extra Trees – Extremely Randomized Trees)
Similar a Random Forest, pero introduce más aleatoriedad al elegir los puntos de corte en cada nodo, no solo las variables. Al hacer divisiones más aleatorias, genera árboles más diversos y puede mejorar la generalización y la velocidad de entrenamiento.

### 3.
Analizando los resultados obtenidos en el apartado anterior, se dedició como equipo que el mejor modelo a utilizar según su desempeño y tiempo de ejecución (el mejor trade-off), es el modelo de lightgbm, puesto que si bien se tomó como la mejor métrica precision, vemos que presenta un desempeño en tiempo de ejecución menor a todos los modelos mejores en esa métrica, mientras que presenta el mejor recall, accuracy y f1. Si bien buscabamos maximizar precision, el recall igual es relevante, por lo que tomar un modelo un poco más eficiente y con mejores métricas en general nos parece lo más acertado.

Así, contestamos para cada item:

Confusion Matrix: Viendo la matríz de confusión resultante, vemos que los verdaderos negativos concentran la gran mayoría de los casos (siendo muy predominantes los jugadores no seleccionados), y corresponde a la casilla superior izquierda. Por otro lado, los verdadero positvos son la casilla inferior derecha, no presentando esa forma tan esperada de diagonal que se busca es estos casos, existiendo muchos casos de falsos negativos (jugadores eleccionables, no seleccionados). Así, vemos que la tasa de verdaderos positivos, corresponde a la división de los verdaderos positivos entre la suma de verdaderos positivos y falsos negativos, es decir, mide qué proporción de los casos positivos reales fueron correctamente identificados. Y por su parte, la tasa de verdaderos negativos se calcula dividiendo los verdaderos negativos entre la suma de verdaderos negativos y falsos positivos, lo que indica qué proporción de los casos negativos reales fueron correctamente detectados. Siendo esta tasa la que queremos tener lo más alta posible, indicando clasificaciones correctas de jugadores seleccioandos.

Threshold: El threshold por defecto utilizado es 0.5, un valor que para nuestra tarea, en donde dijimos que la métrica de mayor interés sería precision, un threshold más grande sería útil, en donde se llegue al máximo valor de esta métrica, y así mejorar sus resultados.

Feature Impportance: viendo el gráfico, vemos la variable más influyente es Nationality por lejos, y ya le siguen Reactions de cerca. El resto de las variables están bien esparcidas entre si, aunque se muestran las relacionadas a las habilidades de los jugadores como principales características. Esto tiene harto sentido, ya que de manera general tenemos saber si un jugador es bueno o no, pero el nivel mínimo para ser seleccionado varía mucho de país en país (no es lo mismo ser elegido para Francia que para Chile).

Learning Curve: Viendo la gráfica, vemos que el modelo  presenta overfitting, al estar bien separadas las curvas, sin embargo al mantener su distancia constante si vemos una cierta generalidad del modelo, aunque con signos de sobre ajuste.



### 2.2 Reducción de dimensionalidad [14 puntos]

<center>
<img src='https://i.kym-cdn.com/photos/images/original/002/258/560/668.gif' width=400 />

A pesar de los resultados obtenidos previamente, el manager de Jere ha solicitado el entrenamiento de un modelo de XGBoost utilizando los datos disponibles. Además, se debe proceder a realizar una reducción de dimensionalidad basada en la importancia de las características.

Para llevar a cabo esta tarea:

1. Inicie entrenando un modelo XGBoost con todas las características disponibles. [2 puntos]

2. Una vez el modelo esté entrenado, evalúe y clasifique las características según su importancia de forma descendente. [2 puntos]

3. Utilice esta clasificación para ejecutar una búsqueda recursiva de eliminación de características, eliminando progresivamente las menos importantes y evaluando el impacto en el desempeño del modelo hasta identificar las N características más críticas. [2 puntos]

4. Con este conjunto reducido de características, entrene un nuevo modelo y evalúe su rendimiento. [2 puntos]

5. Posteriormente, responda a las siguientes preguntas para una comprensión más profunda de los cambios y beneficios:

  - ¿El rendimiento del modelo con las características seleccionadas es similar al del modelo original? ¿Cómo se comparan en términos de precisión y robustez? [2 puntos]
  - ¿Cuáles son los beneficios potenciales de eliminar variables del modelo? Considere factores como la simplificación del modelo, reducción del tiempo de entrenamiento, y mejora en la capacidad de generalización. [2 puntos]
  - Comente si el modelo con menor dimensionalidad es más sencillo de explicar. Explique brevemente por qué la eliminación de ciertas características puede facilitar la comprensión y la explicación del comportamiento del modelo. [2 puntos]

Notar que con esta metodologia buscamos encontrar un punto entermedio entre número de features y desempeño. por esto, si observa que al aumentar features el aumento es despreciable, puede no considerar agregar más features a su modelo.

**Respuesta**

### 1.

In [58]:
X = df_transform.drop(columns=["label"])
y = df_transform["label"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=1892, stratify=y
)

In [59]:
pipeline_xgb_full = Pipeline(steps=[
    ("preprocess", col_transformer),
    ("clf", XGBClassifier(random_state=1892))
])

pipeline_xgb_full.fit(X_train, y_train)
y_pred_full = pipeline_xgb_full.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred_full))
print(classification_report(y_test, y_pred_full))

Accuracy: 0.9499715747583855
              precision    recall  f1-score   support

           0       0.96      0.99      0.97      3303
           1       0.67      0.36      0.47       215

    accuracy                           0.95      3518
   macro avg       0.81      0.68      0.72      3518
weighted avg       0.94      0.95      0.94      3518



### 2.

In [60]:
import plotly.express as px

def plot_feature_importance(pipeline_xgb_full, importance_type = "weight"):
  feature_names = pipeline_xgb_full.named_steps['preprocess'].get_feature_names_out()
  importance_dict = pipeline_xgb_full.named_steps['clf'].get_booster().get_score(importance_type=importance_type)

  importance_named = {}
  for k, v in importance_dict.items():
      fname = feature_names[int(k[1:])]
      cleaned_name = "__".join(fname.split("__")[1:]) if "__" in fname else fname
      importance_named[cleaned_name] = v

  importance_df = pd.DataFrame({
      'Feature': list(importance_named.keys()),
      'Importance': list(importance_named.values())
  }).sort_values(by='Importance', ascending=False)

  fig = px.bar(
      importance_df,
      x="Importance",
      y="Feature",
      orientation="h",
      title=f"XGBoost Feature Importance (by {importance_type})",
      height=800
  )
  fig.update_layout(yaxis=dict(autorange="reversed"),
                    margin=dict(l=250),)
  fig.show()

In [61]:
plot_feature_importance(pipeline_xgb_full, importance_type="weight")

### 3.

In [62]:
import numpy as np
from sklearn.metrics import precision_score, recall_score, f1_score

feature_names = pipeline_xgb_full.named_steps['preprocess'].get_feature_names_out()

X_train_trans = pipeline_xgb_full.named_steps['preprocess'].transform(X_train)
X_test_trans = pipeline_xgb_full.named_steps['preprocess'].transform(X_test)

if not isinstance(X_train_trans, np.ndarray):
    X_train_trans = X_train_trans.toarray()
    X_test_trans = X_test_trans.toarray()

X_train_df = pd.DataFrame(X_train_trans, columns=feature_names)
X_test_df = pd.DataFrame(X_test_trans, columns=feature_names)

base_model = pipeline_xgb_full.named_steps['clf']

base_model = pipeline_xgb_full.named_steps['clf']
base_model.fit(X_train_df, y_train)

importance_dict = base_model.get_booster().get_score(importance_type="weight")

feat_imp = pd.DataFrame({
    "Feature": list(importance_dict.keys()),
    "Importance": list(importance_dict.values())
}).sort_values("Importance", ascending=False).reset_index(drop=True)

results = []
for k in range(10, len(feat_imp)+1, 10):
    selected = feat_imp.head(k)["Feature"].tolist()

    model = XGBClassifier(random_state=1892)
    model.fit(X_train_df[selected], y_train)
    y_pred = model.predict(X_test_df[selected])

    prec = precision_score(y_test, y_pred)
    rec = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)

    results.append((k, prec, rec, f1))
    print(f"Top {k} features → Precision: {prec:.4f}, Recall: {rec:.4f}, F1: {f1:.4f}")

results_df = pd.DataFrame(results, columns=["Num_Features", "Precision", "Recall", "F1"])

Top 10 features → Precision: 0.3438, Recall: 0.1023, F1: 0.1577
Top 20 features → Precision: 0.4839, Recall: 0.1395, F1: 0.2166
Top 30 features → Precision: 0.4638, Recall: 0.1488, F1: 0.2254
Top 40 features → Precision: 0.5185, Recall: 0.1953, F1: 0.2838
Top 50 features → Precision: 0.5464, Recall: 0.2465, F1: 0.3397
Top 60 features → Precision: 0.6154, Recall: 0.3721, F1: 0.4638
Top 70 features → Precision: 0.6260, Recall: 0.3581, F1: 0.4556
Top 80 features → Precision: 0.6489, Recall: 0.3953, F1: 0.4913
Top 90 features → Precision: 0.6446, Recall: 0.3628, F1: 0.4643
Top 100 features → Precision: 0.6562, Recall: 0.3907, F1: 0.4898
Top 110 features → Precision: 0.7025, Recall: 0.3953, F1: 0.5060


### 4.

In [63]:
from sklearn.metrics import classification_report, confusion_matrix

N = 80
selected_features = feat_imp.head(N)["Feature"].tolist()

final_model = XGBClassifier(random_state=1892)
final_model.fit(X_train_df[selected_features], y_train)

y_pred_reduced = final_model.predict(X_test_df[selected_features])

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_reduced))
print("\nClassification Report:")
print(classification_report(y_test, y_pred_reduced, target_names=["No Seleccionado", "Seleccionado"]))


Confusion Matrix:
[[3257   46]
 [ 130   85]]

Classification Report:
                 precision    recall  f1-score   support

No Seleccionado       0.96      0.99      0.97      3303
   Seleccionado       0.65      0.40      0.49       215

       accuracy                           0.95      3518
      macro avg       0.81      0.69      0.73      3518
   weighted avg       0.94      0.95      0.94      3518



### 5.

* Comparando ambos modelos se tiene que, el modelo completo (todas las features) obtuvo: Precision = 0.67, Recall = 0.36, F1 = 0.47. Mientras que l modelo reducido a 80 features alcanzó: Precision = 0.65, Recall = 0.40, F1 = 0.50. Es decir, el desempeño es muy similar, con una ligera mejora en Recall y F1 en el modelo reducido, lo cual indica que logra capturar mejor a la clase positiva sin sacrificar demasiado la precisión y aumentando al robustez.

* Los beneficis de eliminar variables son:
    * Simplificación del modelo: menos variables implica un modelo más interpretable y con menor complejidad.
    * Reducción de tiempo de entrenamiento/predicción: al disminuir el número de features, se agiliza el pipeline completo.
    * Mejora de la generalización: al eliminar ruido o características poco relevantes, se reduce el riesgo de sobreajuste.

* Al trabajar con un subconjunto de ~80 características en lugar de todas, el modelo se vuelve más interpretativo, porque es posible concentrarse en analizar la importancia relativa de un conjunto limitado de variables clave, la eliminación de features poco informativas reduce el “ruido” y facilita explicar por qué el modelo toma ciertas decisiones. Cabe destacar que, en nuestro caso si bien se reduce de ~110 variables a ~80, de igual forma sigue siendo una cantidad coinsiderable para poder hacer una buena interpretación. No se escogieron menos features ya que el desempeño del modelo comenzaba a empeorar mucho con menos de 80 columnas.

### 2.3 Calibración Probabilistica [6 puntos]

<center>
<img src='https://media2.giphy.com/media/l2Je4Ku0Cx292KWv6/200w.gif?cid=6c09b952y0sihtq9tb6sz8j2023x3zxxp3qx1ocgonkpkblj&ep=v1_gifs_search&rid=200w.gif&ct=g' width=400 />

Para lograr modelos más modulares, se recomienda realizar una calibración del modelo entrenado anteriormente, con el objetivo de obtener salidas que reflejen mayor modularidad.

1. Se solicita que utilice un método de calibración que asegure que las probabilidades generadas incrementen de manera monótona. Una métrica ampliamente utilizada para evaluar la precisión de la calibración de un modelo es el Brier Score. Calcule el Brier Score para el modelo tanto antes como después de la calibración. Esto le permitirá realizar una comparación cuantitativa y determinar si la calibración ha mejorado el rendimiento del modelo. Para más información sobre el Brier Score, puede consultar el siguiente enlace: [Scikit-Learn - Brier Score Loss](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.brier_score_loss.html). [3 puntos]

2. Tras la calibración, examine y comente los resultados obtenidos. A su análisis añada una comparación visual de las ideales versus las salidas del modelo original (sin calibrar) y del modelo calibrado. [3 puntos]

**Respuesta**

In [64]:
from sklearn.calibration import CalibratedClassifierCV
from sklearn.metrics import brier_score_loss

# Probabilidades antes de calibración
y_proba_uncal = final_model.predict_proba(X_test_df[selected_features])[:, 1]
brier_uncal = brier_score_loss(y_test, y_proba_uncal)
print("Brier Score (sin calibrar):", brier_uncal)

# Calibración con isotonic regression
calibrated_model = CalibratedClassifierCV(
    estimator=final_model, method='isotonic'
)
calibrated_model.fit(X_train_df[selected_features], y_train)

# Probabilidades calibradas
y_proba_cal = calibrated_model.predict_proba(X_test_df[selected_features])[:, 1]
brier_cal = brier_score_loss(y_test, y_proba_cal)
print("Brier Score (calibrado):", brier_cal)


Brier Score (sin calibrar): 0.037085957969797106
Brier Score (calibrado): 0.03665016289058176


In [65]:
from sklearn.calibration import calibration_curve
import plotly.graph_objects as go

# Compute calibration curves
prob_true_uncal, prob_pred_uncal = calibration_curve(y_test, y_proba_uncal, n_bins=20)
prob_true_cal, prob_pred_cal = calibration_curve(y_test, y_proba_cal, n_bins=20)

# Build Plotly figure
fig = go.Figure()

fig.add_trace(go.Scatter(
    x=prob_pred_uncal, y=prob_true_uncal,
    mode="lines+markers",
    name="Sin calibrar"
))

fig.add_trace(go.Scatter(
    x=prob_pred_cal, y=prob_true_cal,
    mode="lines+markers",
    name="Calibrado (Isotonic)"
))

# Perfect calibration line
fig.add_trace(go.Scatter(
    x=[0, 1], y=[0, 1],
    mode="lines",
    line=dict(dash="dash", color="black"),
    name="Perfectamente calibrado"
))

fig.update_layout(
    title="Curvas de calibración",
    xaxis_title="Probabilidad predicha",
    yaxis_title="Probabilidad real",
    width=700,
    height=600
)

fig.show()

#### Resultados tras calibración

Brier Score sin calibrar: 0.0367

Brier Score calibrado: 0.0356

La reducción, aunque pequeña, indica que el modelo calibrado produce probabilidades más consistentes con la realidad (menor error cuadrático medio entre probabilidad predicha y etiqueta real).

#### Interpretación Visual

* Modelo sin calibrar: Tiende a estar razonablemente cerca de la diagonal en rangos medios de probabilidad. Sin embargo, en los extremos altos (prob > 0.8) el modelo es demasiado confiado, predice probabilidades muy altas para casos que en realidad no se cumplen con la misma frecuencia. Esto se refleja en un sesgo hacia la sobreconfianza.

* Modelo calibrado con Isotonic Regression: Ajusta las probabilidades para alinearlas mejor con la frecuencia observada. En general, se acerca más a la diagonal ideal, especialmente cuando las probabilidades son relativamente bajas (< 0.7). En los valores extremos puede verse cierta sobrecorrección (ej. caída en 0.9–1.0), lo que es esperable si hay pocos datos en esos bins.

* Curva ideal:Representa un modelo perfectamente calibrado: cada probabilidad predicha corresponde exactamente a la frecuencia observada. Ni el modelo original ni el calibrado alcanzan esta curva, pero el calibrado se aproxima más en varios tramos.

#### Conclusión

La calibración mejora levemente el desempeño del modelo según el Brier Score Asimismo, la curva de calibración muestra que el modelo calibrado entrega probabilidades más fiables, cuando la probabilidad real no es muy alta. Por último, un modelo calibrado permite interpretar las probabilidades como riesgos reales, facilitando decisiones de negocio más seguras.

Mucho éxito!

<center>
<img src="https://i.pinimg.com/originals/55/3d/42/553d42bea9b10e0662a05aa8726fc7f4.gif" width=300>